// GENERATED by scripts/gen-protocol-version.mjs from package.json `pulseProtocol`.
// Do not edit: change package.json, then run `npm run build`.

export const PULSE_PROTOCOL: { version: string; min: number; max: number } = {
  version: '2.2',
  min: 2,
  max: 2,
};
