import type {
  FastifyPluginAsync,
  FastifyPluginOptions,
  FastifyReply,
  FastifyRequest,
  FastifySchema,
} from 'fastify';
import {
  createPulseVaultCore,
  PROTOCOL_VERSION,
  type PulseVaultCoreCacheOptions,
} from '../core.js';
import type {
  PulseVaultOnUploadComplete,
  PulseVaultOnArtifactEvent,
} from '../lib/pulsevaultTus.js';
import type { PulseVaultValidatePayload } from '../lib/magic.js';
import { type PulseVaultAuthorize } from '../lib/authorize.js';
import type { PulseVaultAllowedExtensions } from '../lib/options.js';
import type { PulseVaultStorage, UploadKind } from '../storage/types.js';

export type {
  PulseVaultAuthorize,
  PulseVaultAuthorizeContext,
  PulseVaultAuthorizePhase,
} from '../lib/authorize.js';

// Mirrored in the opt-in `./augment.ts` re-export (for consumers who `import
// "@mieweb/pulsevault/augment"`) and kept here too so this plugin typechecks
// standalone even if the consumer never imports that module.
declare module 'fastify' {
  interface FastifyRequest {
    pulseVault?: { artifactId: string; kind: UploadKind; relatedTo?: string };
  }
}

export type PulseVaultRoutesOptions = {
  storage: PulseVaultStorage;
  maxUploadSize: number;
  allowedExtensions: PulseVaultAllowedExtensions;
  cache?: PulseVaultCoreCacheOptions;
  authorize?: PulseVaultAuthorize;
  validatePayload?: PulseVaultValidatePayload;
  onUploadComplete?: PulseVaultOnUploadComplete;
  onArtifactEvent?: PulseVaultOnArtifactEvent;
} & FastifyPluginOptions;

// Adds the OpenAPI-flavored fields without pulling `@fastify/swagger` into this
// plugin's type surface; consumers who do register it get the real module
// augmentation and these become native.
type OpenApiRouteSchema = FastifySchema & {
  tags?: string[];
  summary?: string;
  description?: string;
};

const pulseVaultErrorResponse = {
  type: 'object',
  properties: {
    ok: { type: 'boolean' },
    error: { type: 'string' },
  },
  required: ['ok', 'error'],
};

const tusRouteSchema: OpenApiRouteSchema = {
  tags: ['pulsevault'],
  summary: 'TUS resumable upload endpoint',
  description:
    'TUS v1 resumable upload protocol.\n\n' +
    '- `POST` creates a new upload. The `Upload-Metadata` header must include base64-encoded key/value pairs:\n' +
    '  - `artifactId` (or the legacy `videoid`/`projectid` aliases) — a UUID generated by your server.\n' +
    "  - `filename` — original filename; the extension must match the kind's allowed list.\n" +
    '  - `kind` — `video` (default), `project`, `captions`, or `thumbnail`. Determines the storage subdir and which completion hooks fire.\n' +
    "  - `relatedTo` — optional UUID of another artifact this one belongs to (e.g. a merged video's captions/beat-manifest/thumbnail, or a clip belonging to a segment ordering manifest's session).\n" +
    '  - `checksum` — optional `<algorithm>:<hex digest>` of the finished file, verified post-upload if a checksum validator is configured.\n' +
    '- `PATCH` appends a chunk at the offset given by `Upload-Offset`, with `Content-Type: application/offset+octet-stream`.\n' +
    '- `HEAD` returns the current offset for a resumable upload.\n' +
    '- `DELETE` cancels an in-flight upload.\n\n' +
    'See https://tus.io/protocols/resumable-upload for the full protocol.',
  response: {
    400: { description: 'Invalid request.', ...pulseVaultErrorResponse },
    403: {
      description: 'Authorize hook rejected the request.',
      ...pulseVaultErrorResponse,
    },
  },
};

const artifactDeleteSchema: OpenApiRouteSchema = {
  tags: ['pulsevault'],
  summary: 'Delete an uploaded artifact',
  description:
    'Deletes all storage for an artifactId (bytes + sidecar metadata), regardless of kind. Runs the `authorize` hook with `phase: "delete"` before the adapter\'s `remove` is called. Returns 204 on success, 404 if the artifactId was unknown, 501 if the adapter does not implement `remove`.',
  params: {
    type: 'object',
    properties: {
      artifactId: {
        type: 'string',
        format: 'uuid',
        description: 'UUID of the upload to delete.',
      },
    },
    required: ['artifactId'],
  },
  response: {
    400: {
      description: '`artifactId` is not a valid UUID.',
      ...pulseVaultErrorResponse,
    },
    403: {
      description: 'Authorize hook rejected the request.',
      ...pulseVaultErrorResponse,
    },
    404: { description: 'Artifact not found.', ...pulseVaultErrorResponse },
    501: {
      description: 'Storage adapter does not implement delete.',
      ...pulseVaultErrorResponse,
    },
  },
};

const artifactGetSchema: OpenApiRouteSchema = {
  tags: ['pulsevault'],
  summary: 'Serve a previously uploaded artifact',
  description:
    "Resolves the `artifactId` through the configured storage adapter and either streams the bytes or redirects (for CDN-backed adapters). The artifact's kind (video, project, or captions) is resolved from storage, not the URL. Runs the `authorize` hook before resolve.",
  params: {
    type: 'object',
    properties: {
      artifactId: {
        type: 'string',
        format: 'uuid',
        description: 'UUID returned from the upload flow.',
      },
    },
    required: ['artifactId'],
  },
  querystring: {
    type: 'object',
    properties: {
      token: {
        type: 'string',
        description:
          'Optional bearer token for pre-authenticated watch links. Forwarded to the `authorize` hook as `ctx.token` so parent servers can validate it without a separate login step.',
      },
    },
  },
  response: {
    400: {
      description: '`artifactId` is not a valid UUID.',
      ...pulseVaultErrorResponse,
    },
    403: {
      description: 'Authorize hook rejected the request.',
      ...pulseVaultErrorResponse,
    },
    404: { description: 'Artifact not found.', ...pulseVaultErrorResponse },
  },
};

const capabilitiesSchema: OpenApiRouteSchema = {
  tags: ['pulsevault'],
  summary: "Discover this deployment's protocol version and configuration",
  description:
    'Unauthenticated — the response carries no secrets. Lets a client detect protocol compatibility before pairing.',
  response: {
    200: {
      type: 'object',
      properties: {
        protocolVersion: { type: 'number' },
        minSupportedVersion: { type: 'number' },
        maxSupportedVersion: { type: 'number' },
        kinds: { type: 'array', items: { type: 'string' } },
        allowedExtensions: {
          type: 'object',
          properties: {
            video: { type: 'array', items: { type: 'string' } },
            project: { type: 'array', items: { type: 'string' } },
            captions: { type: 'array', items: { type: 'string' } },
            thumbnail: { type: 'array', items: { type: 'string' } },
          },
        },
        maxUploadSize: { type: 'number' },
        checksum: {
          type: 'object',
          properties: { algorithms: { type: 'array', items: { type: 'string' } } },
        },
        // Present only when the storage adapter supports the §9 direct-upload
        // profile — without this declaration Fastify's response serializer
        // strips the field and clients never see the capability.
        directUpload: {
          type: 'object',
          properties: { enabled: { type: 'boolean' } },
        },
      },
    },
  },
};

// Fastify doesn't type route params from the schema alone, so `:artifactId` comes through as `unknown`.
type ArtifactIdParams = { artifactId?: unknown };

const directUploadCreateSchema: OpenApiRouteSchema = {
  tags: ['pulsevault'],
  summary: 'Create a presigned direct upload (PROTOCOL.md §9)',
  description:
    'Reserves an artifactId (same collision rules as a TUS create) and returns a presigned PUT URL the client uploads the bytes to directly — the data plane bypasses this server. Requires a storage adapter with direct-upload support (the S3/R2 adapter); local-filesystem deployments return 501.',
  body: {
    type: 'object',
    required: ['artifactId', 'filename', 'size'],
    properties: {
      artifactId: { type: 'string', format: 'uuid' },
      filename: { type: 'string' },
      kind: { type: 'string', enum: ['video', 'project', 'captions', 'thumbnail'] },
      relatedTo: { type: 'string', format: 'uuid' },
      checksum: { type: 'string', description: '`<algorithm>:<hex digest>` of the finished file.' },
      name: { type: 'string', description: 'Free-form display title (session anchor only).' },
      size: { type: 'integer', minimum: 1, description: 'Exact byte count; signed into the URL.' },
    },
  },
  response: {
    400: { description: 'Invalid request.', ...pulseVaultErrorResponse },
    403: { description: 'Authorize hook rejected the request.', ...pulseVaultErrorResponse },
    409: { description: 'artifactId already has an upload.', ...pulseVaultErrorResponse },
    413: { description: '`size` exceeds the maximum upload size.', ...pulseVaultErrorResponse },
    501: {
      description: 'Storage adapter has no direct-upload support.',
      ...pulseVaultErrorResponse,
    },
  },
};

const directUploadCompleteSchema: OpenApiRouteSchema = {
  tags: ['pulsevault'],
  summary: 'Confirm a presigned direct upload (PROTOCOL.md §9)',
  description:
    'Verifies the stored object matches the declared size, then runs the same validate → markReady → onUploadComplete sequence as a finished TUS upload. Idempotent: completing an already-ready artifact returns 200 without re-running hooks.',
  params: {
    type: 'object',
    properties: { artifactId: { type: 'string', format: 'uuid' } },
    required: ['artifactId'],
  },
  response: {
    400: { description: 'Invalid artifactId.', ...pulseVaultErrorResponse },
    403: { description: 'Authorize hook rejected the request.', ...pulseVaultErrorResponse },
    404: { description: 'Unknown artifactId.', ...pulseVaultErrorResponse },
    409: {
      description: 'No uploaded object found for this artifactId.',
      ...pulseVaultErrorResponse,
    },
    422: {
      description: 'Stored object failed validation (size/checksum/sniff).',
      ...pulseVaultErrorResponse,
    },
    501: {
      description: 'Storage adapter has no direct-upload support.',
      ...pulseVaultErrorResponse,
    },
  },
};

/** Coerce the raw route param to a string; an invalid UUID is rejected by the core's own check either way. */
function paramToString(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

const pulseVaultRoutes: FastifyPluginAsync<PulseVaultRoutesOptions> = async (fastify, opts) => {
  const {
    storage,
    maxUploadSize,
    allowedExtensions,
    cache,
    authorize,
    validatePayload,
    onUploadComplete,
    onArtifactEvent,
  } = opts;

  // All hook orchestration, tus glue, and artifact GET/DELETE logic lives in
  // the framework-agnostic core (`../core.js`); this file only wires Fastify's
  // routing/schema/lifecycle around it, so behavior can't drift from the
  // `./core` entry point non-Fastify hosts use.
  const core = createPulseVaultCore({
    storage,
    // `fastify.prefix` is `""` when the plugin is mounted at the root.
    basePath: fastify.prefix,
    maxUploadSize,
    allowedExtensions,
    cache,
    authorize,
    validatePayload,
    onUploadComplete,
    onArtifactEvent,
    logger: fastify.log,
  });

  fastify.addContentTypeParser('application/offset+octet-stream', (_request, _payload, done) => {
    done(null);
  });

  const tusMethods = ['POST', 'PATCH', 'HEAD', 'DELETE', 'OPTIONS'] as const;
  const tusHandler = async (request: FastifyRequest, reply: FastifyReply) => {
    // The core writes directly to the raw response (tus dispatch, authorize
    // rejections, error translation) — hijack so Fastify doesn't also try to
    // manage this reply afterward.
    reply.hijack();
    await core.handleTus(request.raw, reply.raw);
  };
  fastify.route({
    method: [...tusMethods],
    url: '/upload',
    schema: tusRouteSchema,
    handler: tusHandler,
  });
  fastify.route({
    method: [...tusMethods],
    url: '/upload/*',
    schema: tusRouteSchema,
    handler: tusHandler,
  });

  fastify.get('/capabilities', { schema: capabilitiesSchema }, async (request, reply) => {
    reply.hijack();
    await core.handleCapabilities(request.raw, reply.raw);
  });

  fastify.delete(
    '/artifacts/:artifactId',
    { schema: artifactDeleteSchema },
    async (request, reply) => {
      const artifactId = paramToString((request.params as ArtifactIdParams)?.artifactId);
      reply.hijack();
      await core.handleArtifactDelete(request.raw, reply.raw, artifactId);
    },
  );

  fastify.get('/artifacts/:artifactId', { schema: artifactGetSchema }, async (request, reply) => {
    const artifactId = paramToString((request.params as ArtifactIdParams)?.artifactId);
    const token = (request.query as { token?: string })?.token;
    reply.hijack();
    await core.handleArtifactGet(request.raw, reply.raw, artifactId, token);
  });

  // Direct-upload profile (PROTOCOL.md §9). Fastify already parsed the JSON
  // body, so these call the core's data-level entry points instead of the raw
  // handlers (which would try to re-read the drained request stream).
  //
  // Plugin-scoped error shaping: schema-validation rejections fire BEFORE the
  // handlers (so their `.header(...)` chains never run), and a rejected core
  // promise would otherwise hit Fastify's default handler — both must still
  // answer in the protocol's error shape, Protocol-Version stamped, with 5xx
  // internals kept server-side.
  fastify.setErrorHandler((error, request, reply) => {
    const e = error as { statusCode?: unknown; message?: unknown };
    const statusCode = typeof e.statusCode === 'number' && e.statusCode >= 400 ? e.statusCode : 500;
    if (statusCode >= 500) request.log.error({ err: error }, 'pulsevault route failed');
    const message =
      statusCode >= 500
        ? 'Internal Server Error'
        : typeof e.message === 'string' && e.message
          ? e.message
          : 'Bad Request';
    return reply
      .header('Protocol-Version', String(PROTOCOL_VERSION))
      .code(statusCode)
      .send({ ok: false, error: message });
  });

  fastify.post('/direct-uploads', { schema: directUploadCreateSchema }, async (request, reply) => {
    const result = await core.directUploadCreate(request, request.body);
    return reply
      .header('Protocol-Version', String(PROTOCOL_VERSION))
      .code(result.statusCode)
      .send(result.body);
  });

  fastify.post(
    '/direct-uploads/:artifactId/complete',
    { schema: directUploadCompleteSchema },
    async (request, reply) => {
      const artifactId = paramToString((request.params as ArtifactIdParams)?.artifactId);
      const result = await core.directUploadComplete(request, artifactId);
      return reply
        .header('Protocol-Version', String(PROTOCOL_VERSION))
        .code(result.statusCode)
        .send(result.body);
    },
  );
};

export default pulseVaultRoutes;
